### ISSUE TITLE
 revert a recent change made to the folder name for Project 1

### ISSUE THREAD

**Issue by poterlowicz-lab** [elixir-europe/biohackathon-projects-2023#4]
Please revert a recent change made to the folder name for Project 1. It was changed from "01" to "1". Due to this alteration, the Biohackathon Europe webpage now points to an empty page: https://github.com/elixir-europe/biohackathon-projects-2023/tree/main/1.

**Comment by mbaudis** [comment]
I've renamed this - since if listing by project number the non-padding is really running against the grain of naming conventions.

(Saying this as one of the leads for project 1 / 01, whom shouldn't care).

**Comment by poterlowicz-lab** [comment]
If we name the folder '01', the link to the project 1 on https://biohackathon-europe.org/projects.html leads to a 404 error. Therefore, an issue has been raised

**Comment by mbaudis** [comment]
Fixed the links; pushed; external deep links, well, should have recognized ╮(╯▽╰)╭
