### ISSUE TITLE
Where to edit the manuscript? 😅

### ISSUE THREAD

**Issue by matuskalas** [elixir-europe/biohackathon-projects-2023#66]
@beatrizserrano @annefou, should the manuscipt still be editted in the HackMD, or somehow in a PR here (what would then spam all leads of all projects)?

**Comment by beatrizserrano** [comment]
The HackMD is not up to date anymore, let's do it here: https://github.com/beatrizserrano/bh2023-preprint

That will make it easier for the pdf generation as well. And we avoid spamming 😄
